[build-system]
requires = ["hatchling", "hatch-vcs", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[project]
name = "nsls2api"
dynamic = ["version","dependencies"]
description = ''
readme = "README.md"
requires-python = ">=3.9"
license = "BSD-3-Clause"
keywords = []
authors = [
  { name = "Stuart Campbell", email = "scampbell@bnl.gov" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: BSD License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
#dependencies = [
#  "hatch",
#  "hatch-requirements-txt",
#  "hatch-vcs",
#  "typer",
#]

[project.scripts]
nsls2api = "nsls2api.cli.cli:app"

[tool.hatch]
version.source = "vcs"
build.hooks.vcs.version-file = "src/nsls2api/_version.py"

[tool.hatch.metadata.hooks.requirements_txt]
files = ["requirements.txt"]

#[tool.hatch.metadata.hooks.requirements_txt.optional-dependencies]
#dev = ["requirements-dev.txt"]

[tool.black]
target_version = ['py311']
include = '\.pyi?$'

[tool.ruff]
target-version = "py311"

