name: CI

on: 
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"

    steps:
      - uses: actions/checkout@v4

      # Install Kerberos dependencies (for N2SNUserTools)
      - name: Install krb5-devel
        run: sudo apt-get -y install libkrb5-dev

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install
        run: | 
          pip install .

      # This requirements-dev.txt is too much for this step - will trim later.
      - name: Install test requirements
        run: | 
          pip install -r requirements-dev.txt

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: "8.0.0"

      - name: Test with pytest
        run: |
          pytest -v
      
