name: Check Data Consistency in API between Development and Production
permissions:
  contents: read

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  integration_tests:
    runs-on: self-hosted

    steps:
    - name: Print hostname
      run: echo "The hostname is $(hostname)"

    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Download ijhttp.zip
      run: curl -f -L -o ijhttp.zip "https://jb.gg/ijhttp/latest"

    - name: Unzip ijhttp.zip
      run: unzip -q ijhttp.zip

    - name: Check Beamlines Differences
      run: |
        ./ijhttp/ijhttp \
        ./integration-tests/check_beamlines_differences.http
