name: Integration Tests for Deployed API

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: self-hosted

    steps:
    - name: Print hostname
      run: echo "The hostname is $(hostname)"
      
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '17'
    
    - name: Download ijhttp.zip 
      run: curl -f -L -o ijhttp.zip "https://jb.gg/ijhttp/latest"

    - name: Unzip ijhttp.zip
      run: unzip -q ijhttp.zip

  tests:
    runs-on: self-hosted
    steps:
      - name : Beamline endpoint tests
        run: ./ijhttp/ijhttp --env-file ./integration-tests/http-client.env.json --env production ./integration-tests/check_all_beamlines.http
  
